### ISSUE TITLE
duplicate variable?

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/Introduction#17]
Is there a good reason for the monthly mean surface air pressure variable to be in both the Amon and Emon tables?  It seems that it can appear in the data archive either as ps_amon or ps_emon.
thanks,
Karl

**Comment by martinjuckes** [comment]
I don't think it has any purpose. Probably a relic of confusion at an early stage when CMOR expected `ps` in all tables with model-level data. It should have been deleted.

I've made a note in the cmip7_forward_look repo, so this can be closed.
